name: Link PR YouTrack Issue
on:
  pull_request_target:
    types: [opened]

jobs:
  linkYTIssue:
    name: Link YouTrack Issue
    runs-on: self-hosted
    steps:
      - name: add comment on pr
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })
            
            const branchName = pr.data.head.ref
            const match = branchName.match(/[A-Z]+-\d+/)
            
            if (!match) {
              return github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `Cannot add YouTrack Issue link ðŸ˜“`
              })
            }
            
            const issueId = match[0]
            const link = `https://t.cryptorank.io/issue/${match[0]}`

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `[YouTrack Issue](${link})`
            })
